import type { NoticeBundle } from './types.ts';

const RULE = '='.repeat(78);
const THIN = '-'.repeat(78);

const PREAMBLE = [
  'THIRD PARTY NOTICES',
  '',
  'This file is generated by `npm run notices` at the repository root. Do not edit it',
  'by hand; edit the generator or the license sources it reads and regenerate.',
  '',
  'It covers two kinds of third-party material: the machine-learning model artifacts',
  'this product ships or causes a device to download, and the npm packages it',
  'distributes. Where a package ships a license file, its text appears verbatim.',
  'Where a package declares a license but ships no text — which is the case for',
  'several MIT-licensed packages on npm — the notice is generated from the SPDX text',
  'held in licenses/spdx/ and is labelled as generated.',
].join('\n');

function renderPackageSection(bundle: NoticeBundle): string {
  if (bundle.packages.length === 0) {
    return [
      RULE,
      'NPM PACKAGES',
      RULE,
      '',
      'No third-party npm packages are distributed with this product yet.',
    ].join('\n');
  }

  const blocks = bundle.packages.map((entry) => {
    const header = [
      `${entry.name}@${entry.version}`,
      `License: ${entry.spdxId ?? 'undeclared'}`,
      entry.homepage !== null ? `Homepage: ${entry.homepage}` : null,
      `Shipped by: ${entry.requiredBy.join(', ')}`,
      `Notice text: ${entry.textSource} — ${entry.textProvenance}`,
    ].filter((line): line is string => line !== null);

    return [THIN, ...header, THIN, '', entry.licenseText, ''].join('\n');
  });

  return [RULE, 'NPM PACKAGES', RULE, '', ...blocks].join('\n');
}

function renderModelSection(bundle: NoticeBundle): string {
  if (bundle.models.length === 0) {
    return [RULE, 'MACHINE LEARNING MODELS', RULE, '', 'No model artifacts are shipped.'].join(
      '\n',
    );
  }

  const blocks = bundle.models.map((model) => {
    const artifacts = model.artifacts.map(
      (artifact) =>
        `  - ${artifact.id} (${artifact.consumer}) @ ${artifact.revision}\n    ${artifact.url}`,
    );
    return [
      THIN,
      model.work,
      `License: ${model.spdxId}`,
      model.copyright,
      'Artifacts:',
      ...artifacts,
      THIN,
      '',
      model.licenseText.trimEnd(),
      '',
    ].join('\n');
  });

  return [RULE, 'MACHINE LEARNING MODELS', RULE, '', ...blocks].join('\n');
}

/** Plain text, for the importer CLI to distribute alongside its binary. */
export function renderNoticesText(bundle: NoticeBundle): string {
  return [PREAMBLE, '', renderModelSection(bundle), renderPackageSection(bundle)].join('\n') + '\n';
}

/**
 * Structured, for the app's notices view to render. Same aggregation as the text
 * output, so the two can never disagree about what the product includes.
 */
export function renderNoticesJson(bundle: NoticeBundle): string {
  const doc = {
    $generatedBy: 'npm run notices',
    $doNotEdit: true,
    models: bundle.models.map((model) => ({
      work: model.work,
      spdxId: model.spdxId,
      copyright: model.copyright,
      licenseText: model.licenseText.trimEnd(),
      artifacts: model.artifacts.map((artifact) => ({
        id: artifact.id,
        consumer: artifact.consumer,
        revision: artifact.revision,
        url: artifact.url,
      })),
    })),
    packages: bundle.packages.map((entry) => ({
      name: entry.name,
      version: entry.version,
      spdxId: entry.spdxId,
      homepage: entry.homepage,
      textSource: entry.textSource,
      textProvenance: entry.textProvenance,
      requiredBy: entry.requiredBy,
      licenseText: entry.licenseText,
    })),
  };
  return JSON.stringify(doc, null, 2) + '\n';
}
