/**
 * Public surface of the Takeout importer.
 *
 * Task 2.1 added the fixture corpus, which is the regression suite the rest of Phase 2 is
 * built against, 2.2 the multi-archive traversal that reads a set of parts as one logical
 * export, and 2.3 the sidecar pairing resolver that decides which JSON describes which media
 * file. Task 2.4 added the first half of `MetadataRepair`: a minimal EXIF reader, a sidecar time
 * reader, and the timestamp precedence rule that turns them plus mtime into `captured_at` and
 * `captured_at_src`. Task 2.5 closed out `TakeoutReader` with variant and Live Photo linking,
 * which produces relationships keyed on source paths plus the `assets.kind` of every media file;
 * `resolveLinkHashes` turns those relationships into `variant_of_hash` and `live_pair_hash` once
 * the `Hash` stage has run. Task 2.6 closed out `MetadataRepair` with album reconstruction: the
 * design's folder table, album titles from `metadata.json`, the `Archive` and `Trash` flags with
 * Trash opt-in, and membership keyed on source paths that `resolveAlbumMembers` turns into
 * `album_members` rows. Still to come: derivative and embedding stages (2.7-2.9), the manifest
 * writer (2.10), the end-to-end pipeline (2.11), and the reconciliation report (2.12), which
 * consumes this module's unpaired, contested, overruled, unlinked, ambiguous, skipped, and
 * unresolved reports.
 *
 * The corpus is exported rather than kept private to the tests because it is a shared
 * artifact: every task above asserts against the same declared expectations, and a second
 * copy of them would be a second source of truth. Nothing here is bundled by Metro — this
 * package is a Node CLI, so `node:fs` in the graph is fine.
 *
 * `THIRD_PARTY_NOTICES.txt` in this package is generated by `npm run notices` and
 * ships alongside the CLI. MIT requires notice retention; see licenses/README.md.
 */

export {
  ALBUM_METADATA_FILE,
  ARCHIVE_BROWSER_FILE,
  TAKEOUT_DIR_NAME,
  TakeoutFileKind,
  TakeoutTraversalError,
  classifyFileName,
  discoverParts,
  findExportRoot,
  takeoutSourceOf,
  traverseExport,
} from './takeout/traversal.ts';
export type {
  ConflictingCopy,
  DuplicatePath,
  FindExportRootOptions,
  PathConflict,
  TakeoutExport,
  TakeoutFile,
  TakeoutFolder,
  TakeoutPart,
  TraversalMediaKind,
  TraverseOptions,
} from './takeout/traversal.ts';

export {
  PairingStep,
  UnpairedReason,
  basenameOf,
  disambiguatorProbe,
  exactSidecarNames,
  pairExport,
  pairFolder,
  resolveSidecar,
  sidecarStem,
} from './takeout/pairing.ts';
export type {
  PairingClaim,
  PairingResult,
  SidecarCandidate,
  SidecarContest,
  SidecarPairing,
  SidecarResolution,
  UnpairedMedia,
} from './takeout/pairing.ts';

export {
  canCarryReadableExif,
  parseExifCaptureFields,
  parseExifDateTimeMs,
  parseExifOffsetMinutes,
  readExifCaptureFields,
} from './takeout/exif.ts';
export type { ExifCaptureFields, ExifCaptureReader } from './takeout/exif.ts';

export {
  parseAlbumMetadata,
  parseSidecarFlags,
  parseSidecarTimes,
  readAlbumMetadata,
  readSidecarFlags,
  readSidecarTimes,
} from './takeout/sidecar.ts';
export type {
  AlbumMetadata,
  AlbumMetadataReader,
  SidecarFlags,
  SidecarFlagsReader,
  SidecarTimes,
  SidecarTimesReader,
  TakeoutTime,
} from './takeout/sidecar.ts';

export {
  CAPTURED_AT_PRECEDENCE,
  resolveCapturedAt,
  resolveExportTimestamps,
  resolveMediaCapturedAt,
} from './takeout/timestamps.ts';
export type {
  CapturedAtCandidate,
  CapturedAtInputs,
  CapturedAtResolution,
  ResolveTimestampsOptions,
} from './takeout/timestamps.ts';

export {
  EDITED_SUFFIXES,
  LinkRelation,
  UnlinkedVariantReason,
  VariantMatch,
  baseNameFor,
  editedSuffixOf,
  excludedFromTimeline,
  isEditedVariantName,
  isLiveMotionExtension,
  isLiveStillExtension,
  linkExport,
  linkFolder,
  resolveLinkHashes,
  splitExtension,
} from './takeout/variants.ts';
export type {
  AmbiguousLivePair,
  AssetLinks,
  ContentHashLookup,
  EditedSuffixMatch,
  LinkOptions,
  LinkResult,
  LivePair,
  ResolvedLinks,
  UnlinkedVariant,
  UnresolvedLink,
  VariantLink,
} from './takeout/variants.ts';

export {
  FlagSource,
  FolderRole,
  TAKEOUT_ALBUM_ID_PREFIX,
  albumRecordsOf,
  folderRoleOf,
  reconstructAlbums,
  reconstructExportAlbums,
  resolveAlbumMembers,
  takeoutAlbumId,
  yearBucketOf,
} from './takeout/albums.ts';
export type {
  AlbumInputs,
  AlbumMemberRow,
  AlbumOptions,
  AlbumRecordOptions,
  AlbumReconstruction,
  DuplicateAlbumMember,
  FolderClassification,
  MediaDisposition,
  ReconstructAlbumsOptions,
  ResolvedAlbumMembers,
  TakeoutAlbum,
  UnresolvedAlbumMember,
} from './takeout/albums.ts';

export {
  CorpusBuildError,
  buildCorpus,
  fixtureAtPath,
  folderDirIn,
} from './takeout/fixtures/buildCorpus.ts';
export type { BuiltCorpus, MaterializedMedia } from './takeout/fixtures/buildCorpus.ts';

export {
  DOWNLOAD_MTIME,
  FIXTURE_IDS,
  PART_001,
  PART_002,
  PART_003,
  TAKEOUT_CORPUS,
  TAKEOUT_MEDIA_ROOT,
  fixtureById,
} from './takeout/fixtures/corpus.ts';

export type {
  AlbumMetadataFixture,
  ExifFixture,
  FolderExpectation,
  FolderFixture,
  GeoFixture,
  MediaExpectation,
  MediaFixture,
  PartFixture,
  SidecarFixture,
  TakeoutCorpus,
} from './takeout/fixtures/corpusTypes.ts';

export {
  SyntheticMediaError,
  exifApp1Segment,
  exifDateToIsoUtc,
  extensionOf,
  syntheticMediaBytes,
} from './takeout/fixtures/syntheticMedia.ts';

export { DerivativeGenerationError, generateImageDerivatives } from './takeout/derivatives.ts';
export type { ImageDerivativesResult } from './takeout/derivatives.ts';

export {
  VideoDerivativeError,
  detectFfmpeg,
  extractVideoPosterFrame,
  resolveFfmpegPath,
  transcodeVideo720p,
} from './takeout/videoDerivatives.ts';
export type { VideoDerivativeOptions } from './takeout/videoDerivatives.ts';

export {
  COARSE_VECTOR_DIM,
  CoarseVectorBuffer,
  DEFAULT_MODEL_ID,
  EmbeddingError,
  RAW_VECTOR_DIM,
  projectAndQuantize,
  projectVector256,
  quantizeInt8,
} from './takeout/embeddings.ts';
export type { CoarseVectorHeader } from './takeout/embeddings.ts';

export {
  ManifestError,
  formatManifestLine,
  groupManifestEntriesByMonth,
  monthOfCapturedAt,
  parseManifestLine,
  reconstructTimelineFromManifest,
} from './takeout/manifest.ts';
export type { ManifestEntry, TimelineItem } from './takeout/manifest.ts';

export {
  buildReconciliationReport,
  formatReconciliationReportSummary,
} from './takeout/reconciliation.ts';
export type {
  ItemSkipDetail,
  ReconciliationReport,
  ReconciliationReportInput,
} from './takeout/reconciliation.ts';

export { TakeoutPipelineError, runTakeoutPipeline } from './takeout/pipeline.ts';
export type { TakeoutImporterOptions } from './takeout/pipeline.ts';

export {
  CLIP_CONTEXT_LENGTH,
  CLIP_INPUT_SIZE,
  ClipOnnxSession,
  resizeToClipInput,
  toClipPixelValues,
} from './takeout/clipOnnx.ts';
